// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCSd2LU36rIJ52Qrs7curWEIKcB7QC5Z9E',
    appId: '1:662459572131:android:404c16a50507f313a04416',
    messagingSenderId: '662459572131',
    projectId: 'instagram-clone-099',
    storageBucket: 'instagram-clone-099.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC1jh7sMWbnDt0Fp-GP-NhsYIwiLJx4WGk',
    appId: '1:662459572131:ios:5e0d6f6338be777da04416',
    messagingSenderId: '662459572131',
    projectId: 'instagram-clone-099',
    storageBucket: 'instagram-clone-099.appspot.com',
    iosClientId: '662459572131-ocub70h0mcaa1buqm82q0kqf0u23vleu.apps.googleusercontent.com',
    iosBundleId: 'com.instaclone.instagramCloneFlutter',
  );
}
